version: "3.4"
services:
    todo-app:
        container_name: dc-todo-app
        build: .
        ports: 
            - 3000:3000
        # depends_on:
        #     - mongodb
        #     - redis
    mongodb:
        image: mongo:4.4.6
        ports: 
            - 27017:27017
        volumes:
            - todo-app-data:/data/db
volumes: 
    todo-app-data:
